[package]
name = "add_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "radd_one"
crate-type = ["cdylib", "rlib"]


[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }